// generated by mBlock5 for <your product>
// codes make you happy

#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  pinMode(2,INPUT);
  pinMode(4,INPUT);
  pinMode(7,INPUT);
  pinMode(8,INPUT);
  pinMode(10,INPUT);
  pinMode(3,OUTPUT);
  pinMode(5,OUTPUT);
  pinMode(6,OUTPUT);
  pinMode(9,OUTPUT);
  while(1) {
      if((digitalRead(2) == 1.000000)  &&  (((digitalRead(4) == 1.000000)  &&  (digitalRead(7) == 0.000000))  &&  ((digitalRead(8) == 1.000000)  &&  (digitalRead(10) == 1.000000)))){
        analogWrite(3,120);
        analogWrite(5,0);
        analogWrite(6,120);
        analogWrite(9,0);

      }
      if((digitalRead(2) == 1.000000)  &&  (((digitalRead(4) == 0.000000)  &&  (digitalRead(7) == 1.000000))  &&  ((digitalRead(8) == 1.000000)  &&  (digitalRead(10) == 1.000000)))){
        analogWrite(3,110);
        analogWrite(5,0);
        analogWrite(6,0);
        analogWrite(9,110);

      }
      if((digitalRead(2) == 1.000000)  &&  (((digitalRead(4) == 1.000000)  &&  (digitalRead(7) == 1.000000))  &&  ((digitalRead(8) == 0.000000)  &&  (digitalRead(10) == 1.000000)))){
        analogWrite(3,0);
        analogWrite(5,110);
        analogWrite(6,110);
        analogWrite(9,0);

      }
      if((digitalRead(2) == 0.000000)  &&  (((digitalRead(4) == 0.000000)  &&  (digitalRead(7) == 0.000000))  &&  ((digitalRead(8) == 1.000000)  &&  (digitalRead(10) == 1.000000)))){
        analogWrite(3,100);
        analogWrite(5,0);
        analogWrite(6,0);
        analogWrite(9,100);

      }
      if((digitalRead(2) == 1.000000)  &&  (((digitalRead(4) == 1.000000)  &&  (digitalRead(7) == 0.000000))  &&  ((digitalRead(8) == 0.000000)  &&  (digitalRead(10) == 0.000000)))){
        analogWrite(3,0);
        analogWrite(5,100);
        analogWrite(6,100);
        analogWrite(9,0);

      }

      _loop();
  }

}

void _loop() {
}

void loop() {
  _loop();
}
